// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://estbxvlrxllsxyqaixdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdGJ4dmxyeGxsc3h5cWFpeGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDcwMjEsImV4cCI6MjA3MDUyMzAyMX0.aZRSvWZRHXKbShgsZ7_2vn2ERSKLTipdsJtSZxdjub0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});